GET http://localhost:5172/books

### Create Book
POST http://localhost:5172/books
Content-Type: application/json

{
  "title": "Dune",
  "author": "Frank Herbert",
  "year": 1965
}

### Delete Book
DELETE http://localhost:5172/books/10
DELETE http://localhost:5172/books/9999


### Update Book
PUT http://localhost:5172/books/8
Content-Type: application/json

{
  "title": "Changes",
  "author": "David Bowie",
  "year": 1971
}

PUT http://localhost:5172/books/9999
Content-Type: application/json

{
  "title": "Unknown Book",
  "author": "Unknown Author",
  "year": 2000
}

### Get Book by Id
GET http://localhost:5172/books/8
GET http://localhost:5172/books/9999